[package]
name = "gde"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sd = "0.7.6"
clap = "3.0.0-beta.2"
thiserror = "1.0.25"
