[package]
name = "gdengine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
thiserror = "1.0.25"
lazy_static = "1.4.0"

[[bin]]
name = "gde"
path = "src/main.rs"
